### ISSUE TITLE
Issues executing against 

### ISSUE THREAD

**Issue by m4wk** [cesar-rodriguez/terrascan#56]
* terrascan version: 2.5.0 (latest in pip)
* Python version: 3.6.5
* Operating System: Win10
* Terraform Version: 0.11.7

### Description

I have been able to successfully execute Terrascan against the /tests/infrastructure/ files included.  When running against simple Terraform templates that that successfully execute both 'terraform plan' and 'terraform apply,' it fails out on every test.  Does it support Terraform 0.11.x?

### What I Did

```
# pathes omitted
C:\<path>\terrascan -l C:\<path> -t all
ERROR: test_aws_alb_listener_certificate (terrascan.checks.encryption.TestEncryption)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "c:\users\<user>\appdata\local\programs\python\python36-32\lib\site-packages\terraform_validate\terraform_validate.py", line 464, in parse_terraform_directory
    hcl.loads(new_terraform)
  File "c:\users\<user>\appdata\local\programs\python\python36-32\lib\site-packages\hcl\api.py", line 62, in loads
    return HclParser().parse(s)
  File "c:\users\<user>\appdata\local\programs\python\python36-32\lib\site-packages\hcl\parser.py", line 307, in parse
    return self.yacc.parse(s, lexer=Lexer())
  File "c:\users\<user>\appdata\local\programs\python\python36-32\lib\site-packages\ply\yacc.py", line 331, in parse
    return self.parseopt_notrack(input, lexer, debug, tracking, tokenfunc)
  File "c:\users\<user>\appdata\local\programs\python\python36-32\lib\site-packages\ply\yacc.py", line 1061, in parseopt_notrack
    lookahead = get_token()     # Get the next token
  File "c:\users\<user>\appdata\local\programs\python\python36-32\lib\site-packages\hcl\lexer.py", line 275, in token
    return self.lex.token()
  File "c:\users\<user>\appdata\local\programs\python\python36-32\lib\site-packages\ply\lex.py", line 406, in token
    newtok = self.lexeoff(tok)
  File "c:\users\<user>\appdata\local\programs\python\python36-32\lib\site-packages\hcl\lexer.py", line 222, in t_heredoc_eof
    _raise_error(t, 'EOF before closing heredoc')
  File "c:\users\<user>\appdata\local\programs\python\python36-32\lib\site-packages\hcl\lexer.py", line 17, in _raise_error
    raise ValueError("Line %d, column %d, index %d: %s" % (lineno, column, lexpos, message))
ValueError: Line 98, column 0, index 2138: EOF before closing heredoc

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\<user>\appdata\local\programs\python\python36-32\lib\site-packages\terrascan\checks\encryption.py", line 20, in setUp
    self.v = terraform_validate.Validator(self.path)
  File "c:\users\<user>\appdata\local\programs\python\python36-32\lib\site-packages\terraform_validate\terraform_validate.py", line 431, in __init__
    self.terraform_config = self.parse_terraform_directory(path)
  File "c:\users\<user>\appdata\local\programs\python\python36-32\lib\site-packages\terraform_validate\terraform_validate.py", line 466, in parse_terraform_directory
    raise TerraformSyntaxException("Invalid terraform configuration in {0}\n{1}".format(os.path.join(directory,file),e))
terraform_validate.terraform_validate.TerraformSyntaxException: Invalid terraform configuration in C:<path>\main.tf
Line 98, column 0, index 2138: EOF before closing heredoc

```

**Comment by cesar-rodriguez** [comment]
It's not dependent on any terraform version. Do you have a sample file I can use to replicate your issue?

**Comment by m4wk** [comment]
Thanks for the quick response.  Attached is the TF and variables files (zipped) I attempted to run TerraScan against.

Are there any plans to integrate outputting results from Terrascan to another format such as HTML, TXT, etc?
[tf.zip](https://github.com/cesar-rodriguez/terrascan/files/1967729/tf.zip)

**Comment by ndarwincorn** [comment]
I'm seeing this as well with heredoc validation. Here's a toy example that repros:

``` HCL
data "template_file" "test" {
  template = <<-EOF
    this
    is
    a
    multiline
    string
  EOF
}

resource "null_resource" "test" {
  provisioner "local-exec" {
    command = "echo '${data.template_file.test.rendered}'"
  }
}
```
```
$ terrascan -l $(pwd) -t all
...
Line 16, column 0, index 232: EOF before closing heredoc
...
```
```
$ terraform validate
(exit 0)
```
```
$ terraform apply
null_resource.test: Creating...
null_resource.test: Provisioning with 'local-exec'...
null_resource.test (local-exec): Executing: ["/bin/sh" "-c" "echo '  this\n  is\n  a\n  multiline\n  string\n'"]
null_resource.test (local-exec):   this
null_resource.test (local-exec):   is
null_resource.test (local-exec):   a
null_resource.test (local-exec):   multiline
null_resource.test (local-exec):   string
```

**Comment by ndarwincorn** [comment]
This is a problem with PyHCL that was maybe* fixed in https://github.com/virtuald/pyhcl/pull/37 ([0.3.10](https://github.com/virtuald/pyhcl/releases/tag/0.3.10)), but since terraform-validate pins its PyHCL dependency to 0.3.9 it's not getting that fix.

I'll see what happens when I force terraform-validate to use PyHCL 0.3.10, and submit a PR there if it doesn't fix it.

\* By issue description, it should've been fixed in https://github.com/virtuald/pyhcl/pull/32 (0.3.8), but that's clearly not the case.

**Comment by cesar-rodriguez** [comment]
I've updated all dependencies to the latest. Hopefully this fixes these issues.
