### ISSUE TITLE
No module named checks.

### ISSUE THREAD

**Issue by nbdelorme** [cesar-rodriguez/terrascan#59]
* terrascan version:  0.1.0
* Python version:   2.7.5
* Operating System:  CentOS 7.2

### Description
Error running to tool for the first time. Unable to locate modules.
```
$ sudo terrascan --location . --tests all
Traceback (most recent call last):
  File "/bin/terrascan", line 7, in <module>
    from terrascan.__main__ import main
  File "/usr/lib/python2.7/site-packages/terrascan/__main__.py", line 5, in <module>
    from .terrascan import main
  File "/usr/lib/python2.7/site-packages/terrascan/terrascan.py", line 10, in <module>
    from terrascan.checks.security_group import TestSecurityGroups
ImportError: No module named checks.security_group

$ ls /usr/lib/python2.7/site-packages/terrascan
checks  __init__.py  __init__.pyc  __main__.py  __main__.pyc  terrascan.py  terrascan.pyc
```

### What I Did to resolve this issue

In /usr/lib/python2.7/site-packages/terrascan/terrascan.py simply remove .terrascan on lines 10-13.

Change from..
```
from terrascan.checks.security_group import TestSecurityGroups
from terrascan.checks.encryption import TestEncryption
from terrascan.checks.logging_and_monitoring import TestLoggingAndMonitoring
from terrascan.checks.public_exposure import TestPublicExposure
```
To ...
```
from .checks.security_group import TestSecurityGroups
from .checks.encryption import TestEncryption
from .checks.logging_and_monitoring import TestLoggingAndMonitoring
from .checks.public_exposure import TestPublicExposure
```

**Comment by liamg-form3** [comment]
This looks like a great project - can we expect a release any time soon which includes this fix?

**Comment by cesar-rodriguez** [comment]
The latest version v0.1.1 should fix this issue. It only works with Python 3.6+ though.
